### PR TITLE
Automated docker build

### PR DESCRIPTION
**Pull request by v0l**
Adds automated docker builds on push to master

### CODE REVIEW

**Comment by staab** [comment]
I don't mind merging, but I can't maintain. Build failed, feel free to troubleshoot and open another PR: https://github.com/coracle-social/dufflepud/actions/runs/4555757142

**Comment by v0l** [comment]
You need to give permissions to actions to read/write in settings > actions > general

**Comment by staab** [comment]
I think that's already done, see below.

Screen Shot 2023-03-29 at 12 45 29 PM

**Comment by v0l** [comment]
Its this one, to do with `GITHUB_TOKEN`
image

**Comment by staab** [comment]
That's grayed out for me, and it's not immediately obvious how to enable it:

Screen Shot 2023-03-29 at 3 47 15 PM

**Pull request merged**
